version: "3.9"

services:
  db:
    image: postgres:13
   

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    command: npm run dev

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
