
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: usocial
      POSTGRES_PASSWORD: usocialpass
      POSTGRES_DB: usocialdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    command: >
      sh -c "
        until nc -z db 5432; do
          echo 'Esperando a que la DB esté lista...';
          sleep 2;
        done &&
        npx prisma migrate deploy &&
        npm run dev
      "

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules/
    working_dir: /app
    command: npm run dev

volumes:
  pgdata:
